site_name: Research
site_description: 'Web3 Foundation Research'
site_author: 'Web3 Foundation'
site_url: 'https://research.web3.foundation'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://research.web3.foundation/en/latest/mathjax-config.js

markdown_extensions:
  - mdx_math
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  font: false
  logo: 'images/w3f_logo.svg'
  feature: false

  # Extra css for further customization
extra_css:
  - 'stylesheets/extra.css'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/w3f/research'
    - type: 'twitter'
      link: 'https://twitter.com/web3foundation'
    - type: 'medium'
      link: 'https://medium.com/web3foundation'
  news:
    - "12.10.19: Alistair will be participating in panel at an event on cross-app communication organized by Near protocol right after Devcon 5."
    - "09.10.19: At Devcon day 1, Fatemeh will give a short presentation about Polkadot's needs for p2p. On day 4, Alistair will give a devcon talk on our availabiltiy and validity scheme. Also on day 4, Alfonso will give a short presentation about governenace."
    - "05.10.19: Alistair will be giving a talk at the NodeTokyo 2019 (https://nodetokyo.jp/)." 
    - "17.09.19: Alistair's poster on GRANDPA has been accepted as an ACM CCS poster and will be pesented in CCS'19 in London."
    - "16.09.19: Alistair will be giving a number of talks in China in the next two weeks."
    - "18.08.19: Handan wrote a paper describing the relevant time technique used in Polkadot’s block production protocol BABE with the title: “Ouroboros Clepsydra: Ouroboros Praos in Universally Composable Relative Time Model” that will be shortly available online."
    - "15.08.19: Syed and Alfonso will hold an exercise session for Polkadot’s bridge design in Copenhagen Blockchain Summer School. In addition, Alfonso will be giving a talk at the Nordic Blockchain Summit 2019."
    - "05.08.19: Alistair, Fatemeh, and Jeff are in Berlin for our networking workshop with Parity."
    - "22.07.19: Alistair gave a number of talks focusing on Polkadot’s Validity and Avalibility scheme in Beijing, Shanghai, Hangzhou, and Chengzhu during Polkadot China tour in July."
    - "28.06.19: Fatemeh is PC member for CBT 2019."
